name: CI

on:
  push:
    branches:
    - action
    tags:
    - '*'

jobs:
  build_and_release:
    name: Run-wrapper
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          override: true
          target: x86_64-unknown-linux-musl

      - name: Build Run-wrapper
        run: >
          sudo bash -c 'apt update && apt install upx binutils -y';
          rustup component add rust-src --toolchain nightly;
          cargo build --release;
          strip -s -R .comment -R .gnu.version --strip-unneeded target/x86_64-unknown-linux-musl/release/Run;
          upx -9 --best target/x86_64-unknown-linux-musl/release/Run -o target/x86_64-unknown-linux-musl/release/Run-upx;
          cp -f target/x86_64-unknown-linux-musl/release/{Run,Run-upx} . ;
          cp -f Run pkgbuild ;

      - name: Build archlinux packages
        uses: countstarlight/arch-makepkg-action@master
        with:
          scripts: |
            cd pkgbuild;
            makepkg -fsCc --noconfirm --nodeps;
            cp -f Run-wrapper*.pkg.* ../ ;
            cd ../ ;

      - name: Release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: Run*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
